### ISSUE TITLE
Is the .RData file meant to be part of the Git repos?

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/3DGliomaAtlas#1]
I'm not sure whether `.RData` contain objects necessary to run the Shiny app or not?  If not, I guess it needs to be removed from the repos and added to `.gitignore`.

If it contains objects needed by the app, then, first, `.RData` should not be used for such purposes.  It should be considered for temporary usage between R sessions on the local machine by a single user.  Also, when someone else wanna run you app locally, the content of `.RData` will clutter up their workspace, which is not what people want.  (FWIW, I never ever save `.RData` when I close my session.)

Instead, save the individual objects you need to RDS files to make it explicit what your data are in this repos.  Use something like:
```r
saveRDS(mut_413, "mut_413.rds")
saveRDS(mut_485, "mut_485.rds")
```
and then read them in using:
```r
mut_413 <- readRDS("mut_413.rds")
mut_485 <- saveRDS("mut_485.rds")
```

Alternatively, put them in an R list and save that:
```r
mutations <- list(mut_413 = mut_413, mut_485 = mut_485)
saveRDS(mutations, "mutations.rds")
```
and then read them in using:
```r
mutations <- readRDS("mutations.rds")
```
where you can access the indivual elements as:
```r
mutations[["mut_413"]]
mutations[["mut_485"]]
```
and so on.

**Comment by HenrikBengtsson** [comment]
I see that you do:

https://github.com/SRHilz/3DGliomaAtlas/blob/32934945ca955c01a30029462ecc37aef0479331/app.R#L16-L18

so maybe you're already aware of this.

**Comment by SRHilz** [comment]
Thanks for noticing this - yes I never use .RData officially (and also typically don't save it), it just snuck in there. I already had it in my .gitignore, but it probably had saved before I even added it? Not sure but I deleted it + .Rhistory. Hopefully it doesn't reappear!
