### ISSUE TITLE
Dockerize Shiny App in order to deploy it on a ShinyProxy serve

### ISSUE THREAD

**Issue by HenrikBengtsson** [SRHilz/3DGliomaAtlas#3]
After having wrapped up the Shiny App in an R package (Issue #2), it should be pretty straightforward(*) to create a Docker container for this Shiny App, which is [required in order to deploy it on a ShinyProxy server](https://www.shinyproxy.io/deploying-apps/) (I never read this far before so this was news to me).

(*) Is should be possible also without an R package, but it'll be more tedious.

**Comment by SRHilz** [comment]
I think we have it set up as a docker container with an image file etc on Docker Hub. You should be able now to just run this from within your docker on the server:

docker pull srhilz28/gliomaatlas3d:latest

Would you be able to try it out and let me know? Thanks!

**Comment by HenrikBengtsson** [comment]
That's good news.  I had to use `docker run` option `-p 3838:3838` to access `0.0.0.0:3838`, which I think ideally should only be `127.0.0.1:3838` (=`localhost:3838`).

```sh
docker run srhilz28/gliomaatlas3d:latest-p 3838:3838
```

I'm getting:

```sh
$ docker --version
Docker version 19.03.8, build afacb8b7f0

$ docker run -p 3838:3838 srhilz28/gliomaatlas3d:latest

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> shiny::runApp('/usr/local/lib/R/site-library/GliomaAtlas3D/shinyApp')
Loading required package: shiny
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE

Listening on http://0.0.0.0:3838
```

Then I can open the app in <http://localhost:3838>.

**Comment by HenrikBengtsson** [comment]
You do want to run something never than R 3.5.1 though.  We're at R 3.6.3, and in three days we're on R 4.0.0.

Do you have the `Dockerfile` on GitHub so I can have a look at it?

**Comment by SRHilz** [comment]
> You do want to run something never than R 3.5.1 though. We're at R 3.6.3, and in three days we're on R 4.0.0.
> 
> Do you have the `Dockerfile` on GitHub so I can have a look at it?

Yes

> That's good news. I had to use `docker run` option `-p 3838:3838` to access `0.0.0.0:3838`, which I think ideally should only be `127.0.0.1:3838` (=`localhost:3838`).
> 
> ```shell
> docker run srhilz28/gliomaatlas3d:latest-p 3838:3838
> ```
> 
> I'm getting:
> 
> ```shell
> $ docker --version
> Docker version 19.03.8, build afacb8b7f0
> 
> $ docker run -p 3838:3838 srhilz28/gliomaatlas3d:latest
> 
> R version 3.5.1 (2018-07-02) -- "Feather Spray"
> Copyright (C) 2018 The R Foundation for Statistical Computing
> Platform: x86_64-pc-linux-gnu (64-bit)
> 
> R is free software and comes with ABSOLUTELY NO WARRANTY.
> You are welcome to redistribute it under certain conditions.
> Type 'license()' or 'licence()' for distribution details.
> 
> R is a collaborative project with many contributors.
> Type 'contributors()' for more information and
> 'citation()' on how to cite R or R packages in publications.
> 
> Type 'demo()' for some demos, 'help()' for on-line help, or
> 'help.start()' for an HTML browser interface to help.
> Type 'q()' to quit R.
> 
> > shiny::runApp('/usr/local/lib/R/site-library/GliomaAtlas3D/shinyApp')
> Loading required package: shiny
> Warning in rgl.init(initValue, onlyNULL) :
>   RGL: unable to open X11 display
> Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
> 
> Listening on http://0.0.0.0:3838
> ```
> 
> Then I can open the app in http://localhost:3838.

Wonderful, great! Does the 3D aspect of it work okay, even though you are getting an RGL warning? I'm guessing that is just warning you that XQuartz isn't able to pop up on the local machine, but that rgl is still running fine in the shiny output?

**Comment by SRHilz** [comment]
> You do want to run something never than R 3.5.1 though. We're at R 3.6.3, and in three days we're on R 4.0.0.
> 
> Do you have the `Dockerfile` on GitHub so I can have a look at it?

Okay, yes, definitely should upgrade, sorry about that. Yes it is the Dockerfile the main directory of this repo https://github.com/SRHilz/3DGliomaAtlas (I stuck it here because I didn't want to put it in the package).

**Comment by HenrikBengtsson** [comment]
Got it.  Let's keep it in this repos for now; we can move it over to the R package later - that way you'll only have only place to worry about in the future.  It think that will work with R, ShinyProxy and Docker Hub.

**Comment by HenrikBengtsson** [comment]
It looks like you wrote the `Dockerfile` as https://www.shinyproxy.io/deploying-apps/ describes :+1:  I'll see if I can go ahead and deploy it on the server right away ... starting drum roll ...

**Comment by HenrikBengtsson** [comment]
So, good news and bad news.  The good news is that I've managed to deploy the app on http://cbi.ucsf.edu/apps/shinyproxy/ and it runs (I use a tweaked [`Dockerfile`](https://github.com/HenrikBengtsson/3DGliomaAtlas/blob/master/Dockerfile) for now).  The bad news is that the generation of the OpenGL figures done by the {rgl} package is not working.  This is probably because we're running on a headless server (which all webservers are).  This was something I kinda anticipated and is one of the reasons why I wanted to set up the R package.  This is most likely related to what we had in https://github.com/SRHilz/GliomaAtlas3D/issues/7.

I'll see if I can add a package test that produces an RGL figure.  If we can get that working locally and on GitHub Actions (which is headless), then, at least, I understand how OpenGL works in headless mode much better.  Right now, `R CMD check --as-cran` doesn't really test the package by running code other than making sure it passes static-code validation.

**Comment by HenrikBengtsson** [comment]
Success: http://cbi.ucsf.edu/apps/shinyproxy/app/GliomaAtlas3D


The problem was that {rgl} wanted to create the OpenGL figures via X11. For example, when running:
```r
$ Rscript tests/plot3Dmodel.R
```
you would see a window popping up which {rgl} used to render the figure.  If we instead do,
```r
$ RGL_USE_NULL=true Rscript tests/plot3Dmodel.R
```
that pop-up window does not appear but the figure is still plotted.  This is what was needed to get the GitHub Actions (also headless) to work, cf. https://github.com/SRHilz/GliomaAtlas3D/issues/7.

I've fixed this in the [`Dockerfile`](https://github.com/HenrikBengtsson/3DGliomaAtlas/blob/master/Dockerfile) by adding a line:

```
# R package 'rgl': produce OpenGL figures in headless mode
ENV RGL_USE_NULL=true
```

Now, when you run it locally you'll find that the pop-up window no longer appears.
```
$ docker run -p 3838:3838 srhilz28/gliomaatlas3d 
```

PS. I used to do {rgl} way way back in time, like a decade or so ago, and my memory on this is now coming back to me.

**Comment by SRHilz** [comment]
So amazing to see it live! And thank you for figuring out that fix - makes sense and good to know. Thank you so much for this - it is so helpful to play with it and see how it reacts through the web server! I think I will do a bit of playing today to see if I can speed up how long it takes the 3D model to load, and will do one more push in the next day or so to get a final version then before we submit. Thank you again!

**Comment by HenrikBengtsson** [comment]
FYI, an alternative link to app is <http://cbi.ucsf.edu/apps/shinyproxy/app_direct/GliomaAtlas3D/> which avoids the CBI top navigator.

* [x] I can also look into increasing the number of CPUs (currently 2) on this virtual machine.  That will lower the risk for slowdowns when multiple users access the app at the same time, but it won't speed things up.

* [x] One thing that could make things a bit snappier is to memoize/cache RGL objects to file so that they don't have to be recreated if access again (e.g. going back and forth between two samples).  In the same vein, one could, in the Dockerfile, pre-create all RGL objects in the Shiny App, cache them to file.  This would avoid having to rebuild those RGLs from scratch.  I'll create an issue on https://github.com/SRHilz/GliomaAtlas3D for this.

**Comment by HenrikBengtsson** [comment]
We've updated the ShinyProxy VM server to have 4 vCPUs and 10 GB of RAM.
